// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAccount = "account"

// Account mapped from table <account>
type Account struct {
	ID        int64  `gorm:"column:id;type:bigint;primaryKey" json:"id"`
	Mobile    string `gorm:"column:mobile;type:varchar(20);not null;index:account_mobile_idx,priority:1" json:"mobile"`
	Email     string `gorm:"column:email;type:varchar(100);not null;index:account_email_idx,priority:1" json:"email"`
	Password  string `gorm:"column:password;type:varchar(64);not null" json:"password"`
	Salt      string `gorm:"column:salt;type:varchar(64);not null" json:"salt"`
	IsDeleted bool   `gorm:"column:is_deleted;type:tinyint(1);not null" json:"is_deleted"`
	Number    string `gorm:"column:number;type:varchar(15);not null;comment:doutok号" json:"number"` // doutok号
}

// TableName Account's table name
func (*Account) TableName() string {
	return TableNameAccount
}
