app:
  name: base-service
  version: 0.0.1-test
  trace_endpoint: http://jaeger:14268/api/traces # jaeger endpoint

server:
  grpc:
    addr: 0.0.0.0:8888

components:
  mysql:
    default:
      host: mysql
      port: 3306
      db_name: doutok
      user: root
      password: root
  redis:
    default:
      dsn: redis:6379
      password: root
  etcd:
    default:
      host: etcd
      port: 2379
  minio:
    default:
      host: 192.168.1.143
      port: 9000
      console_port: 9001
      access_key: root
      secret_key: rootroot
  consul:
    default:
      address: consul:8500

data:
  db_sharding_config:
    file_shortvideo_short_video:
      sharding: file_shortvideo_short_video
      sharding_number: 5
    file_shortvideo_public:
      sharding: file_shortvideo_public
      sharding_number: 5
  db_sharding_tables:
    file:
      domain_name: shortvideo
      biz_sharding_field_config:
        short_video:
          fields:
            - id
            - hash
        public:
          fields:
            - id
            - hash

snowflake:
  node: 1
