version: '3'

networks:
  total:
    driver: bridge

services:
  base-service:
    container_name: base-service
    image: base-service
    volumes:
      - ./configs/baseservice:/app/configs
    networks:
      - total

  sv-api-service:
    container_name: sv-api-service
    image: sv-api-service
    volumes:
      - ./configs/svapiservice:/app/configs
    environment:
      - GOLANG_PROTOBUF_REGISTRATION_CONFLICT=warn
    networks:
      - total