version: '3'

networks:
  total:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - ./mysql/.env
    networks:
      - total
    volumes:
        - ./mysql_data:/var/lib/mysql:rw
        - ./mysql/my.cnf:/etc/mysql/my.cnf
    ports:
        - "3306:3306"
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server /etc/redis/redis.conf
    networks:
      - total
    volumes:
      - ./redis_data:/data
      - ./redis/redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"
    restart: always

  etcd:
    image: bitnami/etcd
    container_name: etcd
    networks:
      - total
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
    ports:
      - "2379:2379"
      - "2380:2380"
    restart: always

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server --console-address ':9001' /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: root
      MINIO_SECRET_KEY: rootroot
    volumes:
      - ./minio_data:/data
      - ./minio:/root/.minio
    networks:
      - total
    privileged: true
    restart: always

  consul:
    container_name: consul
    image: hashicorp/consul:1.15.4
    networks:
      - total
    ports:
      - "8500:8500"
    command: ["consul","agent","-server","-bootstrap","-data-dir","/consul","-ui","-client","0.0.0.0"]