version: "3"

networks:
  total:
    driver: bridge

services:
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
      - "9095:9095"
    volumes:
      - ./loki_data:/var/loki
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
    user: root
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - total

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    ports:
      - "9080:9080"
    volumes:
      - ./promtail/promtail-config.yaml:/promtail-config.yaml
    privileged: true
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 200M
    command: [ "-config.file=/promtail-config.yaml" ]
    networks:
      - total

  grafana:
    image: grafana/grafana:9.5.18
    restart: "always"
    ports:
      - 3000:3000
    container_name: "grafana"
    volumes:
#      - "./grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "./grafana/grafana-storage:/var/lib/grafana"
    networks:
      - total

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - ./tempo_data:/var/tempo
    ports:
      - "14268"  # jaeger ingest
      - "3200"   # tempo
      - "4317"  # otlp grpc
      - "4318"  # otlp http
      - "9411"   # zipkin

  otel:
    container_name: otel
    image: otel/opentelemetry-collector:latest
    command: [ "--config=/etc/otel-collector-config.yml", "${OTELCOL_ARGS}" ]
    volumes:
      - ./otel/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55670:55679" # zpages extension

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"
